pipeline {
    agent any

    triggers {
        cron('H */8 * * *') //regular builds
        pollSCM('* * * * *') //polling for changes, here once a minute
    }

    stages {
        stage('Gradle Build') {
              steps {
                sh './gradlew clean build'
              }
        }
        stage('Unit & Integration Tests') {
            steps {
                 sh './gradlew test'
            }
        }
        stage('Build Image') {
            steps {
                 sh './gradlew bootBuildImage'
            }
        }
        stage('Deploy to Test Env') {
            steps {
                timeout(time: 1, unit:'DAYS') {
                    input 'Deploy to Test?'
                }
            }
        }
        stage('Deploy to Test env') {
            steps {
                echo 'Deploy to Production'
            }
        }
    }
}