pipeline {
    agent any

    triggers {
        cron('H */8 * * *') //regular builds
        pollSCM('* * * * *') //polling for changes, here once a minute
    }

    stages {
        stage('Unit & Integration Tests') {
            steps {
            sh 'echo "Hello World"'
            }
        }
        stage('Promotion') {
            steps {
                timeout(time: 1, unit:'DAYS') {
                    input 'Deploy to Production?'
                }
            }
        }
        stage('Deploy to Production') {
            steps {
                echo 'Deploy to Production'
            }
        }
    }
    post {
//         always { //Send an email to the person that broke the build
//             step([$class                  : 'Mailer',
//                   notifyEveryUnstableBuild: true,
//                   recipients              : [emailextrecipients([[$class: 'CulpritsRecipientProvider'], [$class: 'RequesterRecipientProvider']])].join(' ')])
//         }
//     }
}